# services:
#   database:
#     container_name: database
#     image: postgres:12.8
#     restart: always
#     environment:
#       - POSTGRES_USER=pg
#       - POSTGRES_PASSWORD=pass
#       - POSTGRES_DB=crud
#     ports:
#       - 5432:5432
#     volumes:
#       - db:/var/lib/postgresql/data 

# volumes:
#   db:

services:
    database:
        container_name: postgresDb
        image: postgres:12.8
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - 5432:5432
        volumes:
          - db:/var/lib/postgresql/data
volumes:
    db: